name = "SymbolicMath"
uuid = "7f795c9a-a060-11e8-3c40-91ca51eed19f"
authors = ["Tim Kittel <yoho@posteo.de>"]
version = "0.1.0"

[compat]
Julia >= "0.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
